# repo1/.github/workflows/build.yml

name: 1_Non-Prod Build & Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select Branch"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - qa
          - demo
          - preprod
          - main
          - sandbox
          - vapt

jobs:
  trigger-common-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Common Workflow
        uses: actions/github-script@v5
        with:
          script: |
            await github.actions.createWorkflowDispatch({
              owner: 'your-username',
              repo: 'common-workflows',
              workflow: 'build.yml',
              ref: 'main',
              inputs: {
                branch: '${{ github.event.inputs.branch }}'
              }
            });
