# repo1-workflow.yml

name: Repo 1 Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  trigger-common-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Common Workflow
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.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
 }}
          script: |
            const response = await github.repos.createDispatchEvent({
              owner: 'gulshkr',
              repo: 'common-workflow',
              event_type: 'trigger-common-workflow',
              client_payload: {
                workflow: 'build.yml'
              }
            });
            console.log(response.data);
